### ISSUE TITLE
how can I run this script if billing and resources are in two different tenants?

### ISSUE THREAD

**Issue by sarveswarreddy** [awslabs/resource-discovery-for-azure#2]
Hello,

Can you please suggest, how I can run this script if our setup is as below:

Billing is in different tenant than the subscriptions, and there are multiple subscriptions under same tenant(which is different from billing tenant) and there are multiple resource groups inside each of the subscriptions.

**Comment by Tugarev** [comment]
You should have 0 issues running script in your configuration. It will collect "inventory report including detailed metrics" in subscriptions in one tenant no matter where you have your billing. Just run it second time for another tenant.

**Comment by sarveswarreddy** [comment]
We need to loop through each of the subscriptions in the tenant

$subscriptions = @("subscription1", "subscription2", "subscription3")

foreach ($subscription in $subscriptions) {
    az account set --subscription $subscription
    ./ResourceInventory.ps1 -ConcurrencyLimit 8 -ReportName "$subscription" -TenantID <tenantID> -Appid <appID> -SubscriptionID $subscription -Secret <secretValue>
}
